// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tcptest

import (
	"github.com/dosanma1/forge/go/kit/transport/tcp"
	mock "github.com/stretchr/testify/mock"
)

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type Controller
func (_mock *Controller) Register(registry tcp.Registry) {
	_mock.Called(registry)
	return
}

// Controller_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Controller_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - registry tcp.Registry
func (_e *Controller_Expecter) Register(registry interface{}) *Controller_Register_Call {
	return &Controller_Register_Call{Call: _e.mock.On("Register", registry)}
}

func (_c *Controller_Register_Call) Run(run func(registry tcp.Registry)) *Controller_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tcp.Registry
		if args[0] != nil {
			arg0 = args[0].(tcp.Registry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Controller_Register_Call) Return() *Controller_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *Controller_Register_Call) RunAndReturn(run func(registry tcp.Registry)) *Controller_Register_Call {
	_c.Run(run)
	return _c
}
