// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tcptest

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewErrorHandler creates a new instance of ErrorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorHandler {
	mock := &ErrorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ErrorHandler is an autogenerated mock type for the ErrorHandler type
type ErrorHandler struct {
	mock.Mock
}

type ErrorHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorHandler) EXPECT() *ErrorHandler_Expecter {
	return &ErrorHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type ErrorHandler
func (_mock *ErrorHandler) Handle(ctx context.Context, err error) {
	_mock.Called(ctx, err)
	return
}

// ErrorHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type ErrorHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - err error
func (_e *ErrorHandler_Expecter) Handle(ctx interface{}, err interface{}) *ErrorHandler_Handle_Call {
	return &ErrorHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, err)}
}

func (_c *ErrorHandler_Handle_Call) Run(run func(ctx context.Context, err error)) *ErrorHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ErrorHandler_Handle_Call) Return() *ErrorHandler_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *ErrorHandler_Handle_Call) RunAndReturn(run func(ctx context.Context, err error)) *ErrorHandler_Handle_Call {
	_c.Run(run)
	return _c
}
