// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tcptest

import (
	"context"

	"github.com/dosanma1/forge/go/kit/transport/tcp"
	mock "github.com/stretchr/testify/mock"
)

// NewRegistry creates a new instance of Registry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *Registry {
	mock := &Registry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Registry is an autogenerated mock type for the Registry type
type Registry struct {
	mock.Mock
}

type Registry_Expecter struct {
	mock *mock.Mock
}

func (_m *Registry) EXPECT() *Registry_Expecter {
	return &Registry_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type Registry
func (_mock *Registry) Register(key interface{}, handler tcp.Handler) {
	_mock.Called(key, handler)
	return
}

// Registry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Registry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - key interface{}
//   - handler tcp.Handler
func (_e *Registry_Expecter) Register(key interface{}, handler interface{}) *Registry_Register_Call {
	return &Registry_Register_Call{Call: _e.mock.On("Register", key, handler)}
}

func (_c *Registry_Register_Call) Run(run func(key interface{}, handler tcp.Handler)) *Registry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 tcp.Handler
		if args[1] != nil {
			arg1 = args[1].(tcp.Handler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Registry_Register_Call) Return() *Registry_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *Registry_Register_Call) RunAndReturn(run func(key interface{}, handler tcp.Handler)) *Registry_Register_Call {
	_c.Run(run)
	return _c
}

// RegisterFunc provides a mock function for the type Registry
func (_mock *Registry) RegisterFunc(key interface{}, handler func(context.Context, tcp.Session, []byte) error) {
	_mock.Called(key, handler)
	return
}

// Registry_RegisterFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFunc'
type Registry_RegisterFunc_Call struct {
	*mock.Call
}

// RegisterFunc is a helper method to define mock.On call
//   - key interface{}
//   - handler func(context.Context, tcp.Session, []byte) error
func (_e *Registry_Expecter) RegisterFunc(key interface{}, handler interface{}) *Registry_RegisterFunc_Call {
	return &Registry_RegisterFunc_Call{Call: _e.mock.On("RegisterFunc", key, handler)}
}

func (_c *Registry_RegisterFunc_Call) Run(run func(key interface{}, handler func(context.Context, tcp.Session, []byte) error)) *Registry_RegisterFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 func(context.Context, tcp.Session, []byte) error
		if args[1] != nil {
			arg1 = args[1].(func(context.Context, tcp.Session, []byte) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Registry_RegisterFunc_Call) Return() *Registry_RegisterFunc_Call {
	_c.Call.Return()
	return _c
}

func (_c *Registry_RegisterFunc_Call) RunAndReturn(run func(key interface{}, handler func(context.Context, tcp.Session, []byte) error)) *Registry_RegisterFunc_Call {
	_c.Run(run)
	return _c
}
