// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * EndpointSpecInput represents an endpoint in a resource
 */
export class EndpointSpecInput {
    "method": string;
    "path": string;
    "handler": string;
    "response": string;

    /** Creates a new EndpointSpecInput instance. */
    constructor($$source: Partial<EndpointSpecInput> = {}) {
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("handler" in $$source)) {
            this["handler"] = "";
        }
        if (!("response" in $$source)) {
            this["response"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointSpecInput instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointSpecInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EndpointSpecInput($$parsedSource as Partial<EndpointSpecInput>);
    }
}

/**
 * FieldSpecInput represents a field in a resource
 */
export class FieldSpecInput {
    "name": string;
    "type": string;
    "required": boolean;
    "omitempty": boolean;

    /** Creates a new FieldSpecInput instance. */
    constructor($$source: Partial<FieldSpecInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("required" in $$source)) {
            this["required"] = false;
        }
        if (!("omitempty" in $$source)) {
            this["omitempty"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldSpecInput instance from a string or object.
     */
    static createFrom($$source: any = {}): FieldSpecInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FieldSpecInput($$parsedSource as Partial<FieldSpecInput>);
    }
}

/**
 * FileInfo represents file metadata
 */
export class FileInfo {
    "name": string;
    "isDir": boolean;
    "size": number;

    /** Creates a new FileInfo instance. */
    constructor($$source: Partial<FileInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo($$parsedSource as Partial<FileInfo>);
    }
}

/**
 * InitialProject represents an optional initial project to create within a workspace
 */
export class InitialProject {
    "name": string;

    /**
     * service, application, library
     */
    "projectType": string;

    /**
     * go, nestjs, angular, nextjs, typescript
     */
    "language": string;

    /**
     * helm, cloudrun, firebase (optional for libraries)
     */
    "deployer": string;

    /** Creates a new InitialProject instance. */
    constructor($$source: Partial<InitialProject> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("projectType" in $$source)) {
            this["projectType"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("deployer" in $$source)) {
            this["deployer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InitialProject instance from a string or object.
     */
    static createFrom($$source: any = {}): InitialProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InitialProject($$parsedSource as Partial<InitialProject>);
    }
}

/**
 * Project represents a Forge project
 */
export class Project {
    "id": string;
    "name": string;
    "description": string;
    "imageURL": string;
    "path": string;
    "lastOpen": time$0.Time;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("imageURL" in $$source)) {
            this["imageURL"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("lastOpen" in $$source)) {
            this["lastOpen"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

/**
 * ResourceSpecInput represents a resource in the spec
 */
export class ResourceSpecInput {
    "name": string;
    "basePath": string;
    "version": string;
    "fields": FieldSpecInput[];
    "methods": string[];
    "endpoints": EndpointSpecInput[];

    /** Creates a new ResourceSpecInput instance. */
    constructor($$source: Partial<ResourceSpecInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("basePath" in $$source)) {
            this["basePath"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("fields" in $$source)) {
            this["fields"] = [];
        }
        if (!("methods" in $$source)) {
            this["methods"] = [];
        }
        if (!("endpoints" in $$source)) {
            this["endpoints"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceSpecInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceSpecInput {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField3_0($$parsedSource["fields"]);
        }
        if ("methods" in $$parsedSource) {
            $$parsedSource["methods"] = $$createField4_0($$parsedSource["methods"]);
        }
        if ("endpoints" in $$parsedSource) {
            $$parsedSource["endpoints"] = $$createField5_0($$parsedSource["endpoints"]);
        }
        return new ResourceSpecInput($$parsedSource as Partial<ResourceSpecInput>);
    }
}

/**
 * ServiceSpecInput represents the spec data from the UI
 */
export class ServiceSpecInput {
    "serviceName": string;
    "package": string;
    "resources": ResourceSpecInput[];

    /** Creates a new ServiceSpecInput instance. */
    constructor($$source: Partial<ServiceSpecInput> = {}) {
        if (!("serviceName" in $$source)) {
            this["serviceName"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("resources" in $$source)) {
            this["resources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceSpecInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ServiceSpecInput {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField2_0($$parsedSource["resources"]);
        }
        return new ServiceSpecInput($$parsedSource as Partial<ServiceSpecInput>);
    }
}

// Private type creation functions
const $$createType0 = FieldSpecInput.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = EndpointSpecInput.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ResourceSpecInput.createFrom;
const $$createType6 = $Create.Array($$createType5);
