// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * FileInfo represents file metadata
 */
export class FileInfo {
    "name": string;
    "isDir": boolean;
    "size": number;

    /** Creates a new FileInfo instance. */
    constructor($$source: Partial<FileInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo($$parsedSource as Partial<FileInfo>);
    }
}

/**
 * InitialProject represents an optional initial project to create within a workspace
 */
export class InitialProject {
    "name": string;

    /**
     * service, application, library
     */
    "projectType": string;

    /**
     * go, nestjs, angular, nextjs, typescript
     */
    "language": string;

    /**
     * helm, cloudrun, firebase (optional for libraries)
     */
    "deployer": string;

    /** Creates a new InitialProject instance. */
    constructor($$source: Partial<InitialProject> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("projectType" in $$source)) {
            this["projectType"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("deployer" in $$source)) {
            this["deployer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InitialProject instance from a string or object.
     */
    static createFrom($$source: any = {}): InitialProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InitialProject($$parsedSource as Partial<InitialProject>);
    }
}

/**
 * Project represents a Forge project
 */
export class Project {
    "id": string;
    "name": string;
    "description": string;
    "imageURL": string;
    "path": string;
    "lastOpen": time$0.Time;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("imageURL" in $$source)) {
            this["imageURL"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("lastOpen" in $$source)) {
            this["lastOpen"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}
