// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService handles project operations exposed to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForgeProject checks if a directory contains a forge.json file
 */
export function CheckForgeProject(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(567017732, path);
}

/**
 * CreateGitBranch creates a new git branch and switches to it
 */
export function CreateGitBranch(path: string, branchName: string): $CancellablePromise<void> {
    return $Call.ByID(1212430524, path, branchName);
}

/**
 * CreateProject creates a new project at the given path with proper forge.json structure
 */
export function CreateProject(name: string, path: string, initialProjects: $models.InitialProject[]): $CancellablePromise<$models.Project | null> {
    return $Call.ByID(3794430337, name, path, initialProjects).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteProject deletes a project folder (moves to trash on macOS) and removes from recent list
 */
export function DeleteProject(path: string): $CancellablePromise<void> {
    return $Call.ByID(1959829424, path);
}

/**
 * GetGitBranch returns the current git branch for the given path
 */
export function GetGitBranch(path: string): $CancellablePromise<string> {
    return $Call.ByID(3782054692, path);
}

/**
 * InitGitRepo initializes a git repository in the given path
 */
export function InitGitRepo(path: string): $CancellablePromise<void> {
    return $Call.ByID(3353033358, path);
}

/**
 * IsGitRepo checks if the given path is a git repository
 */
export function IsGitRepo(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(1581521484, path);
}

/**
 * ListDirectory lists files in a directory
 */
export function ListDirectory(path: string): $CancellablePromise<$models.FileInfo[]> {
    return $Call.ByID(3289437907, path).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListGitBranches returns all local git branches for the given path
 */
export function ListGitBranches(path: string): $CancellablePromise<string[]> {
    return $Call.ByID(1498666676, path).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListProjects returns all recent projects, filtering out deleted ones
 */
export function ListProjects(): $CancellablePromise<$models.Project[]> {
    return $Call.ByID(1083075410).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OnStartup is called when the app starts
 */
export function OnStartup(options: application$0.ServiceOptions): $CancellablePromise<void> {
    return $Call.ByID(264003830, options);
}

/**
 * OpenProject opens a project by path and adds it to recent projects
 */
export function OpenProject(path: string): $CancellablePromise<$models.Project | null> {
    return $Call.ByID(3378515093, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ReadFile reads a file from the filesystem
 */
export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1365949130, path);
}

/**
 * RemoveProject removes a project from the recent projects list (does not delete files)
 */
export function RemoveProject(path: string): $CancellablePromise<void> {
    return $Call.ByID(3482417973, path);
}

/**
 * SelectDirectory opens a native directory picker dialog
 */
export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1192844387);
}

/**
 * SwitchGitBranch switches to the specified branch for the given path
 */
export function SwitchGitBranch(path: string, branch: string): $CancellablePromise<void> {
    return $Call.ByID(1859568484, path, branch);
}

/**
 * WriteFile writes content to a file
 */
export function WriteFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1511688169, path, content);
}

// Private type creation functions
const $$createType0 = $models.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FileInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($$createType0);
