package fields

import "fmt"

type Name string

func (f Name) String() string {
	return string(f)
}

func (f Name) Merge(children ...Name) Name {
	merged := f
	for _, child := range children {
		merged = Name(fmt.Sprintf("%s.%s", merged.String(), child.String()))
	}

	return merged
}

const (
	NameAPI                Name = "api"
	NameKey                Name = "key"
	NameService            Name = "service"
	NameRequester          Name = "requester"
	NameRepository         Name = "repository"
	NameUsecase            Name = "usecase"
	NameController         Name = "controller"
	NameContext            Name = "context"
	NameError              Name = "err"
	NameErrors             Name = "errors"
	NameURL                Name = "url"
	NameScheme             Name = "scheme"
	NameHost               Name = "host"
	NameBufferFlushTimeout Name = "buffer-flush-timeout"
	NameConfig             Name = "config"
	NameAddress            Name = "address"
	NameDSN                Name = "dsn"
	NameSource             Name = "source"
	NameTarget             Name = "target"
	NameRegion             Name = "region"
	NameCredentials        Name = "credentials"
	NameClientID           Name = "client-id"
	NameClientSecret       Name = "client-secret"
	NameClient             Name = "client"
	NameCustomer           Name = "customer"
	NameChannel            Name = "channel"
	NameFetcher            Name = "fetcher"
	NameGenerator          Name = "generator"
	NameMethod             Name = "method"
	NamePath               Name = "path"
	NameDecoder            Name = "decoder"
	NameEncoder            Name = "encoder"
	NameEvent              Name = "event"
	NameEndpoints          Name = "endpoints"
	NameTimeout            Name = "timeout"
	NameReply              Name = "reply"
	NameTemplate           Name = "template"
	NameOperator           Name = "operator"
	NameKind               Name = "kind"
	NamePlaceholders       Name = "placeholders"
	NamePlaceholder        Name = "placeholder"
	NameType               Name = "type"
	NameMapper             Name = "mapper"
	NameParser             Name = "parser"
	NameRequest            Name = "request"
	NameHeader             Name = "header"
	NameExternal           Name = "external"
	NameExternalID         Name = "externalID"
	NameExternalIDs        Name = "externalIDs"
	NameGroup              Name = "group"
	NameParent             Name = "parent"
	NameIdentity           Name = "identity"
	NameBody               Name = "body"
	NameData               Name = "data"
	NameIsMergeable        Name = "is-mergeable"
	NameIndex              Name = "index"
	NameConnection         Name = "connection"
	NameSize               Name = "size"
	NameContentType        Name = "content-type"
	NameMeta               Name = "meta"
	NameSession            Name = "session"
	NameUser               Name = "user"
	NameAction             Name = "action"
	NameStatus             Name = "status"
	NameActionType         Name = "actionType"
	NameNodeType           Name = "nodeType"
	NameX                  Name = "x"
	NameWorkspace          Name = "workspace"
	NameCondition          Name = "condition"
	NameBroker             Name = "broker"
	NameDirection          Name = "direction"
	NameOrderType          Name = "orderType"
	NameQuantity           Name = "quantity"
	NameNodes              Name = "nodes"
	NameAppliedPrice       Name = "appliedPrice"
	NamePeriod             Name = "period"
	NameCards              Name = "cards"
	NameContent            Name = "content"
	NameMultiplier         Name = "multiplier"
	NameTimespan           Name = "timespan"
	NamePosition           Name = "position"
	NameLogoURL            Name = "logoURL"
	NameFrom               Name = "from"
	NameComponent          Name = "component"
	NameStartTime          Name = "startTime"
	NameEndTime            Name = "endTime"
	NameStartedAt          Name = "startedAt"
	NameCompletedAt        Name = "completedAt"
	NameSide               Name = "side"
	NameInstrument         Name = "instrument"
	NameSymbol             Name = "symbol"
	NameOrganisation       Name = "organisation"
	NameDomain             Name = "domain"
	NameTenant             Name = "tenant"
)
