// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package persistencetest

import (
	"context"

	"github.com/dosanma1/forge/go/kit/persistence"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactioner creates a new instance of MockTransactioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactioner {
	mock := &MockTransactioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactioner is an autogenerated mock type for the Transactioner type
type MockTransactioner struct {
	mock.Mock
}

type MockTransactioner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactioner) EXPECT() *MockTransactioner_Expecter {
	return &MockTransactioner_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockTransactioner
func (_mock *MockTransactioner) Exec(ctx context.Context, fn persistence.TxFunc) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, persistence.TxFunc) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactioner_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockTransactioner_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - fn persistence.TxFunc
func (_e *MockTransactioner_Expecter) Exec(ctx interface{}, fn interface{}) *MockTransactioner_Exec_Call {
	return &MockTransactioner_Exec_Call{Call: _e.mock.On("Exec", ctx, fn)}
}

func (_c *MockTransactioner_Exec_Call) Run(run func(ctx context.Context, fn persistence.TxFunc)) *MockTransactioner_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 persistence.TxFunc
		if args[1] != nil {
			arg1 = args[1].(persistence.TxFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactioner_Exec_Call) Return(err error) *MockTransactioner_Exec_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactioner_Exec_Call) RunAndReturn(run func(ctx context.Context, fn persistence.TxFunc) error) *MockTransactioner_Exec_Call {
	_c.Call.Return(run)
	return _c
}
