// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: filter/proto/operator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lt            string                 `protobuf:"bytes,1,opt,name=lt,proto3" json:"lt,omitempty"`
	Lte           string                 `protobuf:"bytes,2,opt,name=lte,proto3" json:"lte,omitempty"`
	Gt            string                 `protobuf:"bytes,3,opt,name=gt,proto3" json:"gt,omitempty"`
	Gte           string                 `protobuf:"bytes,4,opt,name=gte,proto3" json:"gte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operator) Reset() {
	*x = Operator{}
	mi := &file_filter_proto_operator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operator) ProtoMessage() {}

func (x *Operator) ProtoReflect() protoreflect.Message {
	mi := &file_filter_proto_operator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operator.ProtoReflect.Descriptor instead.
func (*Operator) Descriptor() ([]byte, []int) {
	return file_filter_proto_operator_proto_rawDescGZIP(), []int{0}
}

func (x *Operator) GetLt() string {
	if x != nil {
		return x.Lt
	}
	return ""
}

func (x *Operator) GetLte() string {
	if x != nil {
		return x.Lte
	}
	return ""
}

func (x *Operator) GetGt() string {
	if x != nil {
		return x.Gt
	}
	return ""
}

func (x *Operator) GetGte() string {
	if x != nil {
		return x.Gte
	}
	return ""
}

var File_filter_proto_operator_proto protoreflect.FileDescriptor

const file_filter_proto_operator_proto_rawDesc = "" +
	"\n" +
	"\x1bfilter/proto/operator.proto\x12\ttb.filter\"N\n" +
	"\bOperator\x12\x0e\n" +
	"\x02lt\x18\x01 \x01(\tR\x02lt\x12\x10\n" +
	"\x03lte\x18\x02 \x01(\tR\x03lte\x12\x0e\n" +
	"\x02gt\x18\x03 \x01(\tR\x02gt\x12\x10\n" +
	"\x03gte\x18\x04 \x01(\tR\x03gteB,Z*github.com/dosanma1/forge/go/kit/filter/pbb\x06proto3"

var (
	file_filter_proto_operator_proto_rawDescOnce sync.Once
	file_filter_proto_operator_proto_rawDescData []byte
)

func file_filter_proto_operator_proto_rawDescGZIP() []byte {
	file_filter_proto_operator_proto_rawDescOnce.Do(func() {
		file_filter_proto_operator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filter_proto_operator_proto_rawDesc), len(file_filter_proto_operator_proto_rawDesc)))
	})
	return file_filter_proto_operator_proto_rawDescData
}

var file_filter_proto_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_filter_proto_operator_proto_goTypes = []any{
	(*Operator)(nil), // 0: tb.filter.Operator
}
var file_filter_proto_operator_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_filter_proto_operator_proto_init() }
func file_filter_proto_operator_proto_init() {
	if File_filter_proto_operator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filter_proto_operator_proto_rawDesc), len(file_filter_proto_operator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filter_proto_operator_proto_goTypes,
		DependencyIndexes: file_filter_proto_operator_proto_depIdxs,
		MessageInfos:      file_filter_proto_operator_proto_msgTypes,
	}.Build()
	File_filter_proto_operator_proto = out.File
	file_filter_proto_operator_proto_goTypes = nil
	file_filter_proto_operator_proto_depIdxs = nil
}
