// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dosanma1/forge/go/kit/monitoring/tracer (interfaces: Span)

// Package tracertest is a generated GoMock package.
package tracertest

import (
	reflect "reflect"
	time "time"

	tracer "github.com/dosanma1/forge/go/kit/monitoring/tracer"
	gomock "github.com/golang/mock/gomock"
)

// MockSpan is a mock of Span interface.
type MockSpan struct {
	ctrl     *gomock.Controller
	recorder *MockSpanMockRecorder
}

// MockSpanMockRecorder is the mock recorder for MockSpan.
type MockSpanMockRecorder struct {
	mock *MockSpan
}

// NewMockSpan creates a new mock instance.
func NewMockSpan(ctrl *gomock.Controller) *MockSpan {
	mock := &MockSpan{ctrl: ctrl}
	mock.recorder = &MockSpanMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpan) EXPECT() *MockSpanMockRecorder {
	return m.recorder
}

// AddEvents mocks base method.
func (m *MockSpan) AddEvents(arg0 ...tracer.Event) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddEvents", varargs...)
}

// AddEvents indicates an expected call of AddEvents.
func (mr *MockSpanMockRecorder) AddEvents(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEvents", reflect.TypeOf((*MockSpan)(nil).AddEvents), arg0...)
}

// Duration mocks base method.
func (m *MockSpan) Duration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Duration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Duration indicates an expected call of Duration.
func (mr *MockSpanMockRecorder) Duration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Duration", reflect.TypeOf((*MockSpan)(nil).Duration))
}

// End mocks base method.
func (m *MockSpan) End() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "End")
}

// End indicates an expected call of End.
func (mr *MockSpanMockRecorder) End() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "End", reflect.TypeOf((*MockSpan)(nil).End))
}

// HasSpanID mocks base method.
func (m *MockSpan) HasSpanID() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSpanID")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasSpanID indicates an expected call of HasSpanID.
func (mr *MockSpanMockRecorder) HasSpanID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSpanID", reflect.TypeOf((*MockSpan)(nil).HasSpanID))
}

// HasTraceID mocks base method.
func (m *MockSpan) HasTraceID() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTraceID")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasTraceID indicates an expected call of HasTraceID.
func (mr *MockSpanMockRecorder) HasTraceID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTraceID", reflect.TypeOf((*MockSpan)(nil).HasTraceID))
}

// SetAttributes mocks base method.
func (m *MockSpan) SetAttributes(arg0 ...tracer.KeyValue) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SetAttributes", varargs...)
}

// SetAttributes indicates an expected call of SetAttributes.
func (mr *MockSpanMockRecorder) SetAttributes(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAttributes", reflect.TypeOf((*MockSpan)(nil).SetAttributes), arg0...)
}

// SetErrorStatus mocks base method.
func (m *MockSpan) SetErrorStatus(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetErrorStatus", arg0)
}

// SetErrorStatus indicates an expected call of SetErrorStatus.
func (mr *MockSpanMockRecorder) SetErrorStatus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetErrorStatus", reflect.TypeOf((*MockSpan)(nil).SetErrorStatus), arg0)
}

// SetOkStatus mocks base method.
func (m *MockSpan) SetOkStatus(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOkStatus", arg0)
}

// SetOkStatus indicates an expected call of SetOkStatus.
func (mr *MockSpanMockRecorder) SetOkStatus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOkStatus", reflect.TypeOf((*MockSpan)(nil).SetOkStatus), arg0)
}

// SpanID mocks base method.
func (m *MockSpan) SpanID() tracer.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpanID")
	ret0, _ := ret[0].(tracer.ID)
	return ret0
}

// SpanID indicates an expected call of SpanID.
func (mr *MockSpanMockRecorder) SpanID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpanID", reflect.TypeOf((*MockSpan)(nil).SpanID))
}

// TraceID mocks base method.
func (m *MockSpan) TraceID() tracer.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TraceID")
	ret0, _ := ret[0].(tracer.ID)
	return ret0
}

// TraceID indicates an expected call of TraceID.
func (mr *MockSpanMockRecorder) TraceID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TraceID", reflect.TypeOf((*MockSpan)(nil).TraceID))
}
