// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package udptest

import (
	"github.com/dosanma1/forge/go/kit/transport/udp"
	mock "github.com/stretchr/testify/mock"
)

// NewRegistry creates a new instance of Registry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *Registry {
	mock := &Registry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Registry is an autogenerated mock type for the Registry type
type Registry struct {
	mock.Mock
}

type Registry_Expecter struct {
	mock *mock.Mock
}

func (_m *Registry) EXPECT() *Registry_Expecter {
	return &Registry_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type Registry
func (_mock *Registry) Register(opcode uint16, handler udp.Handler) {
	_mock.Called(opcode, handler)
	return
}

// Registry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Registry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - opcode uint16
//   - handler udp.Handler
func (_e *Registry_Expecter) Register(opcode interface{}, handler interface{}) *Registry_Register_Call {
	return &Registry_Register_Call{Call: _e.mock.On("Register", opcode, handler)}
}

func (_c *Registry_Register_Call) Run(run func(opcode uint16, handler udp.Handler)) *Registry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint16
		if args[0] != nil {
			arg0 = args[0].(uint16)
		}
		var arg1 udp.Handler
		if args[1] != nil {
			arg1 = args[1].(udp.Handler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Registry_Register_Call) Return() *Registry_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *Registry_Register_Call) RunAndReturn(run func(opcode uint16, handler udp.Handler)) *Registry_Register_Call {
	_c.Run(run)
	return _c
}
