// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package udptest

import (
	"context"
	"net"

	"github.com/dosanma1/forge/go/kit/transport/udp"
	mock "github.com/stretchr/testify/mock"
)

// NewSession creates a new instance of Session. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *Session {
	mock := &Session{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Session is an autogenerated mock type for the Session type
type Session struct {
	mock.Mock
}

type Session_Expecter struct {
	mock *mock.Mock
}

func (_m *Session) EXPECT() *Session_Expecter {
	return &Session_Expecter{mock: &_m.Mock}
}

// CheckResends provides a mock function for the type Session
func (_mock *Session) CheckResends() {
	_mock.Called()
	return
}

// Session_CheckResends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResends'
type Session_CheckResends_Call struct {
	*mock.Call
}

// CheckResends is a helper method to define mock.On call
func (_e *Session_Expecter) CheckResends() *Session_CheckResends_Call {
	return &Session_CheckResends_Call{Call: _e.mock.On("CheckResends")}
}

func (_c *Session_CheckResends_Call) Run(run func()) *Session_CheckResends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Session_CheckResends_Call) Return() *Session_CheckResends_Call {
	_c.Call.Return()
	return _c
}

func (_c *Session_CheckResends_Call) RunAndReturn(run func()) *Session_CheckResends_Call {
	_c.Run(run)
	return _c
}

// Close provides a mock function for the type Session
func (_mock *Session) Close() {
	_mock.Called()
	return
}

// Session_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Session_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Session_Expecter) Close() *Session_Close_Call {
	return &Session_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Session_Close_Call) Run(run func()) *Session_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Session_Close_Call) Return() *Session_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *Session_Close_Call) RunAndReturn(run func()) *Session_Close_Call {
	_c.Run(run)
	return _c
}

// Context provides a mock function for the type Session
func (_mock *Session) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// Session_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type Session_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *Session_Expecter) Context() *Session_Context_Call {
	return &Session_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *Session_Context_Call) Run(run func()) *Session_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Session_Context_Call) Return(context1 context.Context) *Session_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *Session_Context_Call) RunAndReturn(run func() context.Context) *Session_Context_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type Session
func (_mock *Session) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Session_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type Session_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *Session_Expecter) ID() *Session_ID_Call {
	return &Session_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *Session_ID_Call) Run(run func()) *Session_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Session_ID_Call) Return(s string) *Session_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Session_ID_Call) RunAndReturn(run func() string) *Session_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessPacket provides a mock function for the type Session
func (_mock *Session) ProcessPacket(p udp.Packet) error {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPacket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(udp.Packet) error); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Session_ProcessPacket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessPacket'
type Session_ProcessPacket_Call struct {
	*mock.Call
}

// ProcessPacket is a helper method to define mock.On call
//   - p udp.Packet
func (_e *Session_Expecter) ProcessPacket(p interface{}) *Session_ProcessPacket_Call {
	return &Session_ProcessPacket_Call{Call: _e.mock.On("ProcessPacket", p)}
}

func (_c *Session_ProcessPacket_Call) Run(run func(p udp.Packet)) *Session_ProcessPacket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 udp.Packet
		if args[0] != nil {
			arg0 = args[0].(udp.Packet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Session_ProcessPacket_Call) Return(err error) *Session_ProcessPacket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Session_ProcessPacket_Call) RunAndReturn(run func(p udp.Packet) error) *Session_ProcessPacket_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteAddr provides a mock function for the type Session
func (_mock *Session) RemoteAddr() net.Addr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteAddr")
	}

	var r0 net.Addr
	if returnFunc, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}
	return r0
}

// Session_RemoteAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteAddr'
type Session_RemoteAddr_Call struct {
	*mock.Call
}

// RemoteAddr is a helper method to define mock.On call
func (_e *Session_Expecter) RemoteAddr() *Session_RemoteAddr_Call {
	return &Session_RemoteAddr_Call{Call: _e.mock.On("RemoteAddr")}
}

func (_c *Session_RemoteAddr_Call) Run(run func()) *Session_RemoteAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Session_RemoteAddr_Call) Return(addr net.Addr) *Session_RemoteAddr_Call {
	_c.Call.Return(addr)
	return _c
}

func (_c *Session_RemoteAddr_Call) RunAndReturn(run func() net.Addr) *Session_RemoteAddr_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type Session
func (_mock *Session) Send(data []byte) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Session_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Session_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - data []byte
func (_e *Session_Expecter) Send(data interface{}) *Session_Send_Call {
	return &Session_Send_Call{Call: _e.mock.On("Send", data)}
}

func (_c *Session_Send_Call) Run(run func(data []byte)) *Session_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Session_Send_Call) Return(err error) *Session_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Session_Send_Call) RunAndReturn(run func(data []byte) error) *Session_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendReliable provides a mock function for the type Session
func (_mock *Session) SendReliable(data []byte) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SendReliable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Session_SendReliable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReliable'
type Session_SendReliable_Call struct {
	*mock.Call
}

// SendReliable is a helper method to define mock.On call
//   - data []byte
func (_e *Session_Expecter) SendReliable(data interface{}) *Session_SendReliable_Call {
	return &Session_SendReliable_Call{Call: _e.mock.On("SendReliable", data)}
}

func (_c *Session_SendReliable_Call) Run(run func(data []byte)) *Session_SendReliable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Session_SendReliable_Call) Return(err error) *Session_SendReliable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Session_SendReliable_Call) RunAndReturn(run func(data []byte) error) *Session_SendReliable_Call {
	_c.Call.Return(run)
	return _c
}
