// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: resource/proto/resource.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_resource_proto_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_resource_proto_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Resource) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Resource) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ResourceIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceIdentifier) Reset() {
	*x = ResourceIdentifier{}
	mi := &file_resource_proto_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceIdentifier) ProtoMessage() {}

func (x *ResourceIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceIdentifier.ProtoReflect.Descriptor instead.
func (*ResourceIdentifier) Descriptor() ([]byte, []int) {
	return file_resource_proto_resource_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceIdentifier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceIdentifier) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_resource_proto_resource_proto protoreflect.FileDescriptor

const file_resource_proto_resource_proto_rawDesc = "" +
	"\n" +
	"\x1dresource/proto/resource.proto\x12\x02tb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x01\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\tcreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x128\n" +
	"\tdeletedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"8\n" +
	"\x12ResourceIdentifier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04typeB.Z,github.com/dosanma1/forge/go/kit/resource/pbb\x06proto3"

var (
	file_resource_proto_resource_proto_rawDescOnce sync.Once
	file_resource_proto_resource_proto_rawDescData []byte
)

func file_resource_proto_resource_proto_rawDescGZIP() []byte {
	file_resource_proto_resource_proto_rawDescOnce.Do(func() {
		file_resource_proto_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_proto_resource_proto_rawDesc), len(file_resource_proto_resource_proto_rawDesc)))
	})
	return file_resource_proto_resource_proto_rawDescData
}

var file_resource_proto_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_proto_resource_proto_goTypes = []any{
	(*Resource)(nil),              // 0: tb.Resource
	(*ResourceIdentifier)(nil),    // 1: tb.ResourceIdentifier
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_resource_proto_resource_proto_depIdxs = []int32{
	2, // 0: tb.Resource.createdAt:type_name -> google.protobuf.Timestamp
	2, // 1: tb.Resource.updatedAt:type_name -> google.protobuf.Timestamp
	2, // 2: tb.Resource.deletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_resource_proto_resource_proto_init() }
func file_resource_proto_resource_proto_init() {
	if File_resource_proto_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_proto_resource_proto_rawDesc), len(file_resource_proto_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_proto_resource_proto_goTypes,
		DependencyIndexes: file_resource_proto_resource_proto_depIdxs,
		MessageInfos:      file_resource_proto_resource_proto_msgTypes,
	}.Build()
	File_resource_proto_resource_proto = out.File
	file_resource_proto_resource_proto_goTypes = nil
	file_resource_proto_resource_proto_depIdxs = nil
}
