// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: resource/proto/sorting.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortDirection int32

const (
	SortDirection_SORT_UNKNOWN SortDirection = 0
	SortDirection_SORT_ASC     SortDirection = 1
	SortDirection_SORT_DESC    SortDirection = 2
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "SORT_UNKNOWN",
		1: "SORT_ASC",
		2: "SORT_DESC",
	}
	SortDirection_value = map[string]int32{
		"SORT_UNKNOWN": 0,
		"SORT_ASC":     1,
		"SORT_DESC":    2,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_resource_proto_sorting_proto_enumTypes[0].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_resource_proto_sorting_proto_enumTypes[0]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_resource_proto_sorting_proto_rawDescGZIP(), []int{0}
}

type Sort struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Params        map[string]SortDirection `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=tb.resource.SortDirection"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_resource_proto_sorting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_sorting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_resource_proto_sorting_proto_rawDescGZIP(), []int{0}
}

func (x *Sort) GetParams() map[string]SortDirection {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_resource_proto_sorting_proto protoreflect.FileDescriptor

const file_resource_proto_sorting_proto_rawDesc = "" +
	"\n" +
	"\x1cresource/proto/sorting.proto\x12\vtb.resource\"\x94\x01\n" +
	"\x04Sort\x125\n" +
	"\x06params\x18\x01 \x03(\v2\x1d.tb.resource.Sort.ParamsEntryR\x06params\x1aU\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\x0e2\x1a.tb.resource.SortDirectionR\x05value:\x028\x01*>\n" +
	"\rSortDirection\x12\x10\n" +
	"\fSORT_UNKNOWN\x10\x00\x12\f\n" +
	"\bSORT_ASC\x10\x01\x12\r\n" +
	"\tSORT_DESC\x10\x02B.Z,github.com/dosanma1/forge/go/kit/resource/pbb\x06proto3"

var (
	file_resource_proto_sorting_proto_rawDescOnce sync.Once
	file_resource_proto_sorting_proto_rawDescData []byte
)

func file_resource_proto_sorting_proto_rawDescGZIP() []byte {
	file_resource_proto_sorting_proto_rawDescOnce.Do(func() {
		file_resource_proto_sorting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_proto_sorting_proto_rawDesc), len(file_resource_proto_sorting_proto_rawDesc)))
	})
	return file_resource_proto_sorting_proto_rawDescData
}

var file_resource_proto_sorting_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resource_proto_sorting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_proto_sorting_proto_goTypes = []any{
	(SortDirection)(0), // 0: tb.resource.SortDirection
	(*Sort)(nil),       // 1: tb.resource.Sort
	nil,                // 2: tb.resource.Sort.ParamsEntry
}
var file_resource_proto_sorting_proto_depIdxs = []int32{
	2, // 0: tb.resource.Sort.params:type_name -> tb.resource.Sort.ParamsEntry
	0, // 1: tb.resource.Sort.ParamsEntry.value:type_name -> tb.resource.SortDirection
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_resource_proto_sorting_proto_init() }
func file_resource_proto_sorting_proto_init() {
	if File_resource_proto_sorting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_proto_sorting_proto_rawDesc), len(file_resource_proto_sorting_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_proto_sorting_proto_goTypes,
		DependencyIndexes: file_resource_proto_sorting_proto_depIdxs,
		EnumInfos:         file_resource_proto_sorting_proto_enumTypes,
		MessageInfos:      file_resource_proto_sorting_proto_msgTypes,
	}.Build()
	File_resource_proto_sorting_proto = out.File
	file_resource_proto_sorting_proto_goTypes = nil
	file_resource_proto_sorting_proto_depIdxs = nil
}
