// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resttest

import (
	"github.com/dosanma1/forge/go/kit/transport/rest"
	mock "github.com/stretchr/testify/mock"
)

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// BasePath provides a mock function for the type Controller
func (_mock *Controller) BasePath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BasePath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Controller_BasePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BasePath'
type Controller_BasePath_Call struct {
	*mock.Call
}

// BasePath is a helper method to define mock.On call
func (_e *Controller_Expecter) BasePath() *Controller_BasePath_Call {
	return &Controller_BasePath_Call{Call: _e.mock.On("BasePath")}
}

func (_c *Controller_BasePath_Call) Run(run func()) *Controller_BasePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_BasePath_Call) Return(s string) *Controller_BasePath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Controller_BasePath_Call) RunAndReturn(run func() string) *Controller_BasePath_Call {
	_c.Call.Return(run)
	return _c
}

// Endpoints provides a mock function for the type Controller
func (_mock *Controller) Endpoints() []rest.Endpoint {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Endpoints")
	}

	var r0 []rest.Endpoint
	if returnFunc, ok := ret.Get(0).(func() []rest.Endpoint); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rest.Endpoint)
		}
	}
	return r0
}

// Controller_Endpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Endpoints'
type Controller_Endpoints_Call struct {
	*mock.Call
}

// Endpoints is a helper method to define mock.On call
func (_e *Controller_Expecter) Endpoints() *Controller_Endpoints_Call {
	return &Controller_Endpoints_Call{Call: _e.mock.On("Endpoints")}
}

func (_c *Controller_Endpoints_Call) Run(run func()) *Controller_Endpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_Endpoints_Call) Return(endpoints []rest.Endpoint) *Controller_Endpoints_Call {
	_c.Call.Return(endpoints)
	return _c
}

func (_c *Controller_Endpoints_Call) RunAndReturn(run func() []rest.Endpoint) *Controller_Endpoints_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type Controller
func (_mock *Controller) Version() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Controller_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type Controller_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *Controller_Expecter) Version() *Controller_Version_Call {
	return &Controller_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *Controller_Version_Call) Run(run func()) *Controller_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_Version_Call) Return(s string) *Controller_Version_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Controller_Version_Call) RunAndReturn(run func() string) *Controller_Version_Call {
	_c.Call.Return(run)
	return _c
}
