// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resttest

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/swaggest/openapi-go"
)

// NewOpenAPIPreparer creates a new instance of OpenAPIPreparer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOpenAPIPreparer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OpenAPIPreparer {
	mock := &OpenAPIPreparer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OpenAPIPreparer is an autogenerated mock type for the OpenAPIPreparer type
type OpenAPIPreparer struct {
	mock.Mock
}

type OpenAPIPreparer_Expecter struct {
	mock *mock.Mock
}

func (_m *OpenAPIPreparer) EXPECT() *OpenAPIPreparer_Expecter {
	return &OpenAPIPreparer_Expecter{mock: &_m.Mock}
}

// SetupOpenAPIOperation provides a mock function for the type OpenAPIPreparer
func (_mock *OpenAPIPreparer) SetupOpenAPIOperation(oc openapi.OperationContext) error {
	ret := _mock.Called(oc)

	if len(ret) == 0 {
		panic("no return value specified for SetupOpenAPIOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(openapi.OperationContext) error); ok {
		r0 = returnFunc(oc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OpenAPIPreparer_SetupOpenAPIOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupOpenAPIOperation'
type OpenAPIPreparer_SetupOpenAPIOperation_Call struct {
	*mock.Call
}

// SetupOpenAPIOperation is a helper method to define mock.On call
//   - oc openapi.OperationContext
func (_e *OpenAPIPreparer_Expecter) SetupOpenAPIOperation(oc interface{}) *OpenAPIPreparer_SetupOpenAPIOperation_Call {
	return &OpenAPIPreparer_SetupOpenAPIOperation_Call{Call: _e.mock.On("SetupOpenAPIOperation", oc)}
}

func (_c *OpenAPIPreparer_SetupOpenAPIOperation_Call) Run(run func(oc openapi.OperationContext)) *OpenAPIPreparer_SetupOpenAPIOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 openapi.OperationContext
		if args[0] != nil {
			arg0 = args[0].(openapi.OperationContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OpenAPIPreparer_SetupOpenAPIOperation_Call) Return(err error) *OpenAPIPreparer_SetupOpenAPIOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OpenAPIPreparer_SetupOpenAPIOperation_Call) RunAndReturn(run func(oc openapi.OperationContext) error) *OpenAPIPreparer_SetupOpenAPIOperation_Call {
	_c.Call.Return(run)
	return _c
}
