// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dosanma1/forge/go/kit/monitoring/tracer/appinsights (interfaces: TelemetryClient)

// Package appinsights_mock is a generated GoMock package.
package appinsights_mock

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	appinsights "github.com/microsoft/ApplicationInsights-Go/appinsights"
	contracts "github.com/microsoft/ApplicationInsights-Go/appinsights/contracts"
)

// MockTelemetryClient is a mock of TelemetryClient interface.
type MockTelemetryClient struct {
	ctrl     *gomock.Controller
	recorder *MockTelemetryClientMockRecorder
}

// MockTelemetryClientMockRecorder is the mock recorder for MockTelemetryClient.
type MockTelemetryClientMockRecorder struct {
	mock *MockTelemetryClient
}

// NewMockTelemetryClient creates a new mock instance.
func NewMockTelemetryClient(ctrl *gomock.Controller) *MockTelemetryClient {
	mock := &MockTelemetryClient{ctrl: ctrl}
	mock.recorder = &MockTelemetryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelemetryClient) EXPECT() *MockTelemetryClientMockRecorder {
	return m.recorder
}

// Channel mocks base method.
func (m *MockTelemetryClient) Channel() appinsights.TelemetryChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channel")
	ret0, _ := ret[0].(appinsights.TelemetryChannel)
	return ret0
}

// Channel indicates an expected call of Channel.
func (mr *MockTelemetryClientMockRecorder) Channel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channel", reflect.TypeOf((*MockTelemetryClient)(nil).Channel))
}

// Context mocks base method.
func (m *MockTelemetryClient) Context() *appinsights.TelemetryContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(*appinsights.TelemetryContext)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTelemetryClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTelemetryClient)(nil).Context))
}

// InstrumentationKey mocks base method.
func (m *MockTelemetryClient) InstrumentationKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstrumentationKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// InstrumentationKey indicates an expected call of InstrumentationKey.
func (mr *MockTelemetryClientMockRecorder) InstrumentationKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstrumentationKey", reflect.TypeOf((*MockTelemetryClient)(nil).InstrumentationKey))
}

// IsEnabled mocks base method.
func (m *MockTelemetryClient) IsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockTelemetryClientMockRecorder) IsEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockTelemetryClient)(nil).IsEnabled))
}

// SetIsEnabled mocks base method.
func (m *MockTelemetryClient) SetIsEnabled(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetIsEnabled", arg0)
}

// SetIsEnabled indicates an expected call of SetIsEnabled.
func (mr *MockTelemetryClientMockRecorder) SetIsEnabled(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsEnabled", reflect.TypeOf((*MockTelemetryClient)(nil).SetIsEnabled), arg0)
}

// Track mocks base method.
func (m *MockTelemetryClient) Track(arg0 appinsights.Telemetry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Track", arg0)
}

// Track indicates an expected call of Track.
func (mr *MockTelemetryClientMockRecorder) Track(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Track", reflect.TypeOf((*MockTelemetryClient)(nil).Track), arg0)
}

// TrackAvailability mocks base method.
func (m *MockTelemetryClient) TrackAvailability(arg0 string, arg1 time.Duration, arg2 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackAvailability", arg0, arg1, arg2)
}

// TrackAvailability indicates an expected call of TrackAvailability.
func (mr *MockTelemetryClientMockRecorder) TrackAvailability(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackAvailability", reflect.TypeOf((*MockTelemetryClient)(nil).TrackAvailability), arg0, arg1, arg2)
}

// TrackEvent mocks base method.
func (m *MockTelemetryClient) TrackEvent(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackEvent", arg0)
}

// TrackEvent indicates an expected call of TrackEvent.
func (mr *MockTelemetryClientMockRecorder) TrackEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackEvent", reflect.TypeOf((*MockTelemetryClient)(nil).TrackEvent), arg0)
}

// TrackException mocks base method.
func (m *MockTelemetryClient) TrackException(arg0 interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackException", arg0)
}

// TrackException indicates an expected call of TrackException.
func (mr *MockTelemetryClientMockRecorder) TrackException(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackException", reflect.TypeOf((*MockTelemetryClient)(nil).TrackException), arg0)
}

// TrackMetric mocks base method.
func (m *MockTelemetryClient) TrackMetric(arg0 string, arg1 float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackMetric", arg0, arg1)
}

// TrackMetric indicates an expected call of TrackMetric.
func (mr *MockTelemetryClientMockRecorder) TrackMetric(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackMetric", reflect.TypeOf((*MockTelemetryClient)(nil).TrackMetric), arg0, arg1)
}

// TrackRemoteDependency mocks base method.
func (m *MockTelemetryClient) TrackRemoteDependency(arg0, arg1, arg2 string, arg3 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackRemoteDependency", arg0, arg1, arg2, arg3)
}

// TrackRemoteDependency indicates an expected call of TrackRemoteDependency.
func (mr *MockTelemetryClientMockRecorder) TrackRemoteDependency(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackRemoteDependency", reflect.TypeOf((*MockTelemetryClient)(nil).TrackRemoteDependency), arg0, arg1, arg2, arg3)
}

// TrackRequest mocks base method.
func (m *MockTelemetryClient) TrackRequest(arg0, arg1 string, arg2 time.Duration, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackRequest", arg0, arg1, arg2, arg3)
}

// TrackRequest indicates an expected call of TrackRequest.
func (mr *MockTelemetryClientMockRecorder) TrackRequest(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackRequest", reflect.TypeOf((*MockTelemetryClient)(nil).TrackRequest), arg0, arg1, arg2, arg3)
}

// TrackTrace mocks base method.
func (m *MockTelemetryClient) TrackTrace(arg0 string, arg1 contracts.SeverityLevel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackTrace", arg0, arg1)
}

// TrackTrace indicates an expected call of TrackTrace.
func (mr *MockTelemetryClientMockRecorder) TrackTrace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackTrace", reflect.TypeOf((*MockTelemetryClient)(nil).TrackTrace), arg0, arg1)
}
