// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package querytest

import (
	"github.com/dosanma1/forge/go/kit/search/query"
	mock "github.com/stretchr/testify/mock"
)

// NewQuery creates a new instance of Query. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *Query {
	mock := &Query{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Query is an autogenerated mock type for the Query type
type Query struct {
	mock.Mock
}

type Query_Expecter struct {
	mock *mock.Mock
}

func (_m *Query) EXPECT() *Query_Expecter {
	return &Query_Expecter{mock: &_m.Mock}
}

// Equal provides a mock function for the type Query
func (_mock *Query) Equal(another query.Query) bool {
	ret := _mock.Called(another)

	if len(ret) == 0 {
		panic("no return value specified for Equal")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(query.Query) bool); ok {
		r0 = returnFunc(another)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Query_Equal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Equal'
type Query_Equal_Call struct {
	*mock.Call
}

// Equal is a helper method to define mock.On call
//   - another query.Query
func (_e *Query_Expecter) Equal(another interface{}) *Query_Equal_Call {
	return &Query_Equal_Call{Call: _e.mock.On("Equal", another)}
}

func (_c *Query_Equal_Call) Run(run func(another query.Query)) *Query_Equal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 query.Query
		if args[0] != nil {
			arg0 = args[0].(query.Query)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Query_Equal_Call) Return(b bool) *Query_Equal_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Query_Equal_Call) RunAndReturn(run func(another query.Query) bool) *Query_Equal_Call {
	_c.Call.Return(run)
	return _c
}

// Filters provides a mock function for the type Query
func (_mock *Query) Filters() query.Filters[any] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Filters")
	}

	var r0 query.Filters[any]
	if returnFunc, ok := ret.Get(0).(func() query.Filters[any]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(query.Filters[any])
		}
	}
	return r0
}

// Query_Filters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filters'
type Query_Filters_Call struct {
	*mock.Call
}

// Filters is a helper method to define mock.On call
func (_e *Query_Expecter) Filters() *Query_Filters_Call {
	return &Query_Filters_Call{Call: _e.mock.On("Filters")}
}

func (_c *Query_Filters_Call) Run(run func()) *Query_Filters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Query_Filters_Call) Return(filters query.Filters[any]) *Query_Filters_Call {
	_c.Call.Return(filters)
	return _c
}

func (_c *Query_Filters_Call) RunAndReturn(run func() query.Filters[any]) *Query_Filters_Call {
	_c.Call.Return(run)
	return _c
}

// IncludedResourceObjects provides a mock function for the type Query
func (_mock *Query) IncludedResourceObjects() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IncludedResourceObjects")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// Query_IncludedResourceObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncludedResourceObjects'
type Query_IncludedResourceObjects_Call struct {
	*mock.Call
}

// IncludedResourceObjects is a helper method to define mock.On call
func (_e *Query_Expecter) IncludedResourceObjects() *Query_IncludedResourceObjects_Call {
	return &Query_IncludedResourceObjects_Call{Call: _e.mock.On("IncludedResourceObjects")}
}

func (_c *Query_IncludedResourceObjects_Call) Run(run func()) *Query_IncludedResourceObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Query_IncludedResourceObjects_Call) Return(strings []string) *Query_IncludedResourceObjects_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *Query_IncludedResourceObjects_Call) RunAndReturn(run func() []string) *Query_IncludedResourceObjects_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function for the type Query
func (_mock *Query) Merge(q query.Query) {
	_mock.Called(q)
	return
}

// Query_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type Query_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - q query.Query
func (_e *Query_Expecter) Merge(q interface{}) *Query_Merge_Call {
	return &Query_Merge_Call{Call: _e.mock.On("Merge", q)}
}

func (_c *Query_Merge_Call) Run(run func(q query.Query)) *Query_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 query.Query
		if args[0] != nil {
			arg0 = args[0].(query.Query)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Query_Merge_Call) Return() *Query_Merge_Call {
	_c.Call.Return()
	return _c
}

func (_c *Query_Merge_Call) RunAndReturn(run func(q query.Query)) *Query_Merge_Call {
	_c.Run(run)
	return _c
}

// Pagination provides a mock function for the type Query
func (_mock *Query) Pagination() *query.PaginationParams {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pagination")
	}

	var r0 *query.PaginationParams
	if returnFunc, ok := ret.Get(0).(func() *query.PaginationParams); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*query.PaginationParams)
		}
	}
	return r0
}

// Query_Pagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pagination'
type Query_Pagination_Call struct {
	*mock.Call
}

// Pagination is a helper method to define mock.On call
func (_e *Query_Expecter) Pagination() *Query_Pagination_Call {
	return &Query_Pagination_Call{Call: _e.mock.On("Pagination")}
}

func (_c *Query_Pagination_Call) Run(run func()) *Query_Pagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Query_Pagination_Call) Return(paginationParams *query.PaginationParams) *Query_Pagination_Call {
	_c.Call.Return(paginationParams)
	return _c
}

func (_c *Query_Pagination_Call) RunAndReturn(run func() *query.PaginationParams) *Query_Pagination_Call {
	_c.Call.Return(run)
	return _c
}

// Sorting provides a mock function for the type Query
func (_mock *Query) Sorting() *query.SortingParams {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sorting")
	}

	var r0 *query.SortingParams
	if returnFunc, ok := ret.Get(0).(func() *query.SortingParams); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*query.SortingParams)
		}
	}
	return r0
}

// Query_Sorting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sorting'
type Query_Sorting_Call struct {
	*mock.Call
}

// Sorting is a helper method to define mock.On call
func (_e *Query_Expecter) Sorting() *Query_Sorting_Call {
	return &Query_Sorting_Call{Call: _e.mock.On("Sorting")}
}

func (_c *Query_Sorting_Call) Run(run func()) *Query_Sorting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Query_Sorting_Call) Return(sortingParams *query.SortingParams) *Query_Sorting_Call {
	_c.Call.Return(sortingParams)
	return _c
}

func (_c *Query_Sorting_Call) RunAndReturn(run func() *query.SortingParams) *Query_Sorting_Call {
	_c.Call.Return(run)
	return _c
}
