# Mockery configuration for API Docs Backend
# This is the global configuration that covers shared library interfaces
# Each service can have its own .mockery.yaml for service-specific interfaces

dir: "{{.InterfaceDir}}/{{.SrcPackageName}}test"
structname: "{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}test"
filename: "{{ .InterfaceName | snakecase }}_mock.go"
template: testify
template-data:
  unroll-variadic: true

packages:
  github.com/dosanma1/mmo-game/shared/go-kit/monitoring/logger:
    interfaces:
      Logger: {}
  github.com/dosanma1/mmo-game/shared/go-kit/firebase:
    interfaces:
      Client: {}
      AuthAPI: {}
      UserManagement: {}
