// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqldbtest

import (
	"context"
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Client
func (_mock *Client) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Client_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Client_Expecter) Close() *Client_Close_Call {
	return &Client_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Client_Close_Call) Run(run func()) *Client_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Close_Call) Return(err error) *Client_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_Close_Call) RunAndReturn(run func() error) *Client_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Database provides a mock function for the type Client
func (_mock *Client) Database() (*sql.DB, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Database")
	}

	var r0 *sql.DB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*sql.DB, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_Database_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Database'
type Client_Database_Call struct {
	*mock.Call
}

// Database is a helper method to define mock.On call
func (_e *Client_Expecter) Database() *Client_Database_Call {
	return &Client_Database_Call{Call: _e.mock.On("Database")}
}

func (_c *Client_Database_Call) Run(run func()) *Client_Database_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Database_Call) Return(dB *sql.DB, err error) *Client_Database_Call {
	_c.Call.Return(dB, err)
	return _c
}

func (_c *Client_Database_Call) RunAndReturn(run func() (*sql.DB, error)) *Client_Database_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type Client
func (_mock *Client) Ping() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Client_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *Client_Expecter) Ping() *Client_Ping_Call {
	return &Client_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *Client_Ping_Call) Run(run func()) *Client_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Ping_Call) Return(err error) *Client_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_Ping_Call) RunAndReturn(run func() error) *Client_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// PingContext provides a mock function for the type Client
func (_mock *Client) PingContext(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for PingContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_PingContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingContext'
type Client_PingContext_Call struct {
	*mock.Call
}

// PingContext is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Client_Expecter) PingContext(context1 interface{}) *Client_PingContext_Call {
	return &Client_PingContext_Call{Call: _e.mock.On("PingContext", context1)}
}

func (_c *Client_PingContext_Call) Run(run func(context1 context.Context)) *Client_PingContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_PingContext_Call) Return(err error) *Client_PingContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_PingContext_Call) RunAndReturn(run func(context1 context.Context) error) *Client_PingContext_Call {
	_c.Call.Return(run)
	return _c
}
