// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqldbtest

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewContextAwarePinger creates a new instance of ContextAwarePinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContextAwarePinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContextAwarePinger {
	mock := &ContextAwarePinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ContextAwarePinger is an autogenerated mock type for the ContextAwarePinger type
type ContextAwarePinger struct {
	mock.Mock
}

type ContextAwarePinger_Expecter struct {
	mock *mock.Mock
}

func (_m *ContextAwarePinger) EXPECT() *ContextAwarePinger_Expecter {
	return &ContextAwarePinger_Expecter{mock: &_m.Mock}
}

// PingContext provides a mock function for the type ContextAwarePinger
func (_mock *ContextAwarePinger) PingContext(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for PingContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ContextAwarePinger_PingContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingContext'
type ContextAwarePinger_PingContext_Call struct {
	*mock.Call
}

// PingContext is a helper method to define mock.On call
//   - context1 context.Context
func (_e *ContextAwarePinger_Expecter) PingContext(context1 interface{}) *ContextAwarePinger_PingContext_Call {
	return &ContextAwarePinger_PingContext_Call{Call: _e.mock.On("PingContext", context1)}
}

func (_c *ContextAwarePinger_PingContext_Call) Run(run func(context1 context.Context)) *ContextAwarePinger_PingContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ContextAwarePinger_PingContext_Call) Return(err error) *ContextAwarePinger_PingContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ContextAwarePinger_PingContext_Call) RunAndReturn(run func(context1 context.Context) error) *ContextAwarePinger_PingContext_Call {
	_c.Call.Return(run)
	return _c
}
