// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqldbtest

import (
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewDatabaseProvider creates a new instance of DatabaseProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseProvider {
	mock := &DatabaseProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DatabaseProvider is an autogenerated mock type for the DatabaseProvider type
type DatabaseProvider struct {
	mock.Mock
}

type DatabaseProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *DatabaseProvider) EXPECT() *DatabaseProvider_Expecter {
	return &DatabaseProvider_Expecter{mock: &_m.Mock}
}

// Database provides a mock function for the type DatabaseProvider
func (_mock *DatabaseProvider) Database() (*sql.DB, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Database")
	}

	var r0 *sql.DB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*sql.DB, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseProvider_Database_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Database'
type DatabaseProvider_Database_Call struct {
	*mock.Call
}

// Database is a helper method to define mock.On call
func (_e *DatabaseProvider_Expecter) Database() *DatabaseProvider_Database_Call {
	return &DatabaseProvider_Database_Call{Call: _e.mock.On("Database")}
}

func (_c *DatabaseProvider_Database_Call) Run(run func()) *DatabaseProvider_Database_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DatabaseProvider_Database_Call) Return(dB *sql.DB, err error) *DatabaseProvider_Database_Call {
	_c.Call.Return(dB, err)
	return _c
}

func (_c *DatabaseProvider_Database_Call) RunAndReturn(run func() (*sql.DB, error)) *DatabaseProvider_Database_Call {
	_c.Call.Return(run)
	return _c
}
