// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqldbtest

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPinger creates a new instance of Pinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Pinger {
	mock := &Pinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Pinger is an autogenerated mock type for the Pinger type
type Pinger struct {
	mock.Mock
}

type Pinger_Expecter struct {
	mock *mock.Mock
}

func (_m *Pinger) EXPECT() *Pinger_Expecter {
	return &Pinger_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type Pinger
func (_mock *Pinger) Ping() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pinger_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Pinger_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *Pinger_Expecter) Ping() *Pinger_Ping_Call {
	return &Pinger_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *Pinger_Ping_Call) Run(run func()) *Pinger_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Pinger_Ping_Call) Return(err error) *Pinger_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pinger_Ping_Call) RunAndReturn(run func() error) *Pinger_Ping_Call {
	_c.Call.Return(run)
	return _c
}
