// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: transport/grpc/proto/health.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_Status int32

const (
	HealthResponse_S_UNHEALTHY HealthResponse_Status = 0
	HealthResponse_S_HEALTHY   HealthResponse_Status = 1
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "S_UNHEALTHY",
		1: "S_HEALTHY",
	}
	HealthResponse_Status_value = map[string]int32{
		"S_UNHEALTHY": 0,
		"S_HEALTHY":   1,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_grpc_proto_health_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_transport_grpc_proto_health_proto_enumTypes[0]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_transport_grpc_proto_health_proto_rawDescGZIP(), []int{1, 0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_transport_grpc_proto_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_proto_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_proto_health_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=tb.health.HealthResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_transport_grpc_proto_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_proto_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_proto_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_S_UNHEALTHY
}

var File_transport_grpc_proto_health_proto protoreflect.FileDescriptor

const file_transport_grpc_proto_health_proto_rawDesc = "" +
	"\n" +
	"!transport/grpc/proto/health.proto\x12\ttb.health\"\x0f\n" +
	"\rHealthRequest\"t\n" +
	"\x0eHealthResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .tb.health.HealthResponse.StatusR\x06status\"(\n" +
	"\x06Status\x12\x0f\n" +
	"\vS_UNHEALTHY\x10\x00\x12\r\n" +
	"\tS_HEALTHY\x10\x012N\n" +
	"\rHealthService\x12=\n" +
	"\x06Status\x12\x18.tb.health.HealthRequest\x1a\x19.tb.health.HealthResponseB4Z2github.com/dosanma1/forge/go/kit/transport/grpc/pbb\x06proto3"

var (
	file_transport_grpc_proto_health_proto_rawDescOnce sync.Once
	file_transport_grpc_proto_health_proto_rawDescData []byte
)

func file_transport_grpc_proto_health_proto_rawDescGZIP() []byte {
	file_transport_grpc_proto_health_proto_rawDescOnce.Do(func() {
		file_transport_grpc_proto_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_grpc_proto_health_proto_rawDesc), len(file_transport_grpc_proto_health_proto_rawDesc)))
	})
	return file_transport_grpc_proto_health_proto_rawDescData
}

var file_transport_grpc_proto_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transport_grpc_proto_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transport_grpc_proto_health_proto_goTypes = []any{
	(HealthResponse_Status)(0), // 0: tb.health.HealthResponse.Status
	(*HealthRequest)(nil),      // 1: tb.health.HealthRequest
	(*HealthResponse)(nil),     // 2: tb.health.HealthResponse
}
var file_transport_grpc_proto_health_proto_depIdxs = []int32{
	0, // 0: tb.health.HealthResponse.status:type_name -> tb.health.HealthResponse.Status
	1, // 1: tb.health.HealthService.Status:input_type -> tb.health.HealthRequest
	2, // 2: tb.health.HealthService.Status:output_type -> tb.health.HealthResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transport_grpc_proto_health_proto_init() }
func file_transport_grpc_proto_health_proto_init() {
	if File_transport_grpc_proto_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_grpc_proto_health_proto_rawDesc), len(file_transport_grpc_proto_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_grpc_proto_health_proto_goTypes,
		DependencyIndexes: file_transport_grpc_proto_health_proto_depIdxs,
		EnumInfos:         file_transport_grpc_proto_health_proto_enumTypes,
		MessageInfos:      file_transport_grpc_proto_health_proto_msgTypes,
	}.Build()
	File_transport_grpc_proto_health_proto = out.File
	file_transport_grpc_proto_health_proto_goTypes = nil
	file_transport_grpc_proto_health_proto_depIdxs = nil
}
