// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ctrltest

import (
	"context"

	"github.com/dosanma1/forge/go/kit/search/query"
	mock "github.com/stretchr/testify/mock"
)

// NewDeleter creates a new instance of Deleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Deleter {
	mock := &Deleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Deleter is an autogenerated mock type for the Deleter type
type Deleter struct {
	mock.Mock
}

type Deleter_Expecter struct {
	mock *mock.Mock
}

func (_m *Deleter) EXPECT() *Deleter_Expecter {
	return &Deleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type Deleter
func (_mock *Deleter) Delete(context1 context.Context, options []query.Option) (string, error) {
	ret := _mock.Called(context1, options)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []query.Option) (string, error)); ok {
		return returnFunc(context1, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []query.Option) string); ok {
		r0 = returnFunc(context1, options)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []query.Option) error); ok {
		r1 = returnFunc(context1, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Deleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Deleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - options []query.Option
func (_e *Deleter_Expecter) Delete(context1 interface{}, options interface{}) *Deleter_Delete_Call {
	return &Deleter_Delete_Call{Call: _e.mock.On("Delete", context1, options)}
}

func (_c *Deleter_Delete_Call) Run(run func(context1 context.Context, options []query.Option)) *Deleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []query.Option
		if args[1] != nil {
			arg1 = args[1].([]query.Option)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Deleter_Delete_Call) Return(s string, err error) *Deleter_Delete_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Deleter_Delete_Call) RunAndReturn(run func(context1 context.Context, options []query.Option) (string, error)) *Deleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}
