// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ctrltest

import (
	"context"

	"github.com/dosanma1/forge/go/kit/resource"
	"github.com/dosanma1/forge/go/kit/search/query"
	mock "github.com/stretchr/testify/mock"
)

// NewGetter creates a new instance of Getter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetter[R resource.Resource](t interface {
	mock.TestingT
	Cleanup(func())
}) *Getter[R] {
	mock := &Getter[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Getter is an autogenerated mock type for the Getter type
type Getter[R resource.Resource] struct {
	mock.Mock
}

type Getter_Expecter[R resource.Resource] struct {
	mock *mock.Mock
}

func (_m *Getter[R]) EXPECT() *Getter_Expecter[R] {
	return &Getter_Expecter[R]{mock: &_m.Mock}
}

// Get provides a mock function for the type Getter
func (_mock *Getter[R]) Get(ctx context.Context, opts []query.Option) (R, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 R
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []query.Option) (R, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []query.Option) R); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(R)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []query.Option) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Getter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Getter_Get_Call[R resource.Resource] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts []query.Option
func (_e *Getter_Expecter[R]) Get(ctx interface{}, opts interface{}) *Getter_Get_Call[R] {
	return &Getter_Get_Call[R]{Call: _e.mock.On("Get", ctx, opts)}
}

func (_c *Getter_Get_Call[R]) Run(run func(ctx context.Context, opts []query.Option)) *Getter_Get_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []query.Option
		if args[1] != nil {
			arg1 = args[1].([]query.Option)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Getter_Get_Call[R]) Return(v R, err error) *Getter_Get_Call[R] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Getter_Get_Call[R]) RunAndReturn(run func(ctx context.Context, opts []query.Option) (R, error)) *Getter_Get_Call[R] {
	_c.Call.Return(run)
	return _c
}
