// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * EndpointSpecInput represents an endpoint in a resource
 */
export class EndpointSpecInput {
    /**
     * Creates a new EndpointSpecInput instance.
     * @param {Partial<EndpointSpecInput>} [$$source = {}] - The source object to create the EndpointSpecInput.
     */
    constructor($$source = {}) {
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("handler" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["handler"] = "";
        }
        if (!("response" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["response"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointSpecInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EndpointSpecInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EndpointSpecInput(/** @type {Partial<EndpointSpecInput>} */($$parsedSource));
    }
}

/**
 * FieldSpecInput represents a field in a resource
 */
export class FieldSpecInput {
    /**
     * Creates a new FieldSpecInput instance.
     * @param {Partial<FieldSpecInput>} [$$source = {}] - The source object to create the FieldSpecInput.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }
        if (!("omitempty" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["omitempty"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldSpecInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FieldSpecInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FieldSpecInput(/** @type {Partial<FieldSpecInput>} */($$parsedSource));
    }
}

/**
 * FileInfo represents file metadata
 */
export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

/**
 * InitialProject represents an optional initial project to create within a workspace
 */
export class InitialProject {
    /**
     * Creates a new InitialProject instance.
     * @param {Partial<InitialProject>} [$$source = {}] - The source object to create the InitialProject.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("projectType" in $$source)) {
            /**
             * service, application, library
             * @member
             * @type {string}
             */
            this["projectType"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * go, nestjs, angular, nextjs, typescript
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("deployer" in $$source)) {
            /**
             * helm, cloudrun, firebase (optional for libraries)
             * @member
             * @type {string}
             */
            this["deployer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InitialProject instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InitialProject}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InitialProject(/** @type {Partial<InitialProject>} */($$parsedSource));
    }
}

/**
 * Project represents a Forge project
 */
export class Project {
    /**
     * Creates a new Project instance.
     * @param {Partial<Project>} [$$source = {}] - The source object to create the Project.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("imageURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imageURL"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("lastOpen" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastOpen"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Project}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project(/** @type {Partial<Project>} */($$parsedSource));
    }
}

/**
 * ResourceSpecInput represents a resource in the spec
 */
export class ResourceSpecInput {
    /**
     * Creates a new ResourceSpecInput instance.
     * @param {Partial<ResourceSpecInput>} [$$source = {}] - The source object to create the ResourceSpecInput.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("basePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["basePath"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {FieldSpecInput[]}
             */
            this["fields"] = [];
        }
        if (!("methods" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["methods"] = [];
        }
        if (!("endpoints" in $$source)) {
            /**
             * @member
             * @type {EndpointSpecInput[]}
             */
            this["endpoints"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceSpecInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResourceSpecInput}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField3_0($$parsedSource["fields"]);
        }
        if ("methods" in $$parsedSource) {
            $$parsedSource["methods"] = $$createField4_0($$parsedSource["methods"]);
        }
        if ("endpoints" in $$parsedSource) {
            $$parsedSource["endpoints"] = $$createField5_0($$parsedSource["endpoints"]);
        }
        return new ResourceSpecInput(/** @type {Partial<ResourceSpecInput>} */($$parsedSource));
    }
}

/**
 * ServiceSpecInput represents the spec data from the UI
 */
export class ServiceSpecInput {
    /**
     * Creates a new ServiceSpecInput instance.
     * @param {Partial<ServiceSpecInput>} [$$source = {}] - The source object to create the ServiceSpecInput.
     */
    constructor($$source = {}) {
        if (!("serviceName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serviceName"] = "";
        }
        if (!("package" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["package"] = "";
        }
        if (!("resources" in $$source)) {
            /**
             * @member
             * @type {ResourceSpecInput[]}
             */
            this["resources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceSpecInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServiceSpecInput}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField2_0($$parsedSource["resources"]);
        }
        return new ServiceSpecInput(/** @type {Partial<ServiceSpecInput>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FieldSpecInput.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = EndpointSpecInput.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ResourceSpecInput.createFrom;
const $$createType6 = $Create.Array($$createType5);
