// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService handles project operations exposed to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForgeProject checks if a directory contains a forge.json file
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckForgeProject(path) {
    return $Call.ByID(567017732, path);
}

/**
 * CreateGitBranch creates a new git branch and switches to it
 * @param {string} path
 * @param {string} branchName
 * @returns {$CancellablePromise<void>}
 */
export function CreateGitBranch(path, branchName) {
    return $Call.ByID(1212430524, path, branchName);
}

/**
 * CreateProject creates a new project at the given path with proper forge.json structure
 * @param {string} name
 * @param {string} path
 * @param {$models.InitialProject[]} initialProjects
 * @returns {$CancellablePromise<$models.Project | null>}
 */
export function CreateProject(name, path, initialProjects) {
    return $Call.ByID(3794430337, name, path, initialProjects).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteProject deletes a project folder (moves to trash on macOS) and removes from recent list
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProject(path) {
    return $Call.ByID(1959829424, path);
}

/**
 * GenerateApp generates a new Angular or Next.js app in the project
 * @param {string} projectPath
 * @param {string} appName
 * @param {string} framework
 * @param {string} deployer
 * @returns {$CancellablePromise<void>}
 */
export function GenerateApp(projectPath, appName, framework, deployer) {
    return $Call.ByID(4098395122, projectPath, appName, framework, deployer);
}

/**
 * GenerateService generates a new Go or NestJS service in the project
 * @param {string} projectPath
 * @param {string} serviceName
 * @param {string} language
 * @param {string} deployer
 * @returns {$CancellablePromise<void>}
 */
export function GenerateService(projectPath, serviceName, language, deployer) {
    return $Call.ByID(3154400698, projectPath, serviceName, language, deployer);
}

/**
 * GetGitBranch returns the current git branch for the given path
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetGitBranch(path) {
    return $Call.ByID(3782054692, path);
}

/**
 * InitGitRepo initializes a git repository in the given path
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function InitGitRepo(path) {
    return $Call.ByID(3353033358, path);
}

/**
 * IsGitRepo checks if the given path is a git repository
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function IsGitRepo(path) {
    return $Call.ByID(1581521484, path);
}

/**
 * ListDirectory lists files in a directory
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function ListDirectory(path) {
    return $Call.ByID(3289437907, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListGitBranches returns all local git branches for the given path
 * @param {string} path
 * @returns {$CancellablePromise<string[]>}
 */
export function ListGitBranches(path) {
    return $Call.ByID(1498666676, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListProjects returns all recent projects, filtering out deleted ones
 * @returns {$CancellablePromise<$models.Project[]>}
 */
export function ListProjects() {
    return $Call.ByID(1083075410).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * OnStartup is called when the app starts
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function OnStartup(options) {
    return $Call.ByID(264003830, options);
}

/**
 * OpenProject opens a project by path and adds it to recent projects
 * @param {string} path
 * @returns {$CancellablePromise<$models.Project | null>}
 */
export function OpenProject(path) {
    return $Call.ByID(3378515093, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ReadFile reads a file from the filesystem
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(1365949130, path);
}

/**
 * RemoveProject removes a project from the recent projects list (does not delete files)
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RemoveProject(path) {
    return $Call.ByID(3482417973, path);
}

/**
 * SaveServiceSpec saves the forge.spec.yaml for a service
 * @param {string} servicePath
 * @param {$models.ServiceSpecInput} specInput
 * @returns {$CancellablePromise<void>}
 */
export function SaveServiceSpec(servicePath, specInput) {
    return $Call.ByID(1228669559, servicePath, specInput);
}

/**
 * SelectDirectory opens a native directory picker dialog
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(1192844387);
}

/**
 * SwitchGitBranch switches to the specified branch for the given path
 * @param {string} path
 * @param {string} branch
 * @returns {$CancellablePromise<void>}
 */
export function SwitchGitBranch(path, branch) {
    return $Call.ByID(1859568484, path, branch);
}

/**
 * WriteFile writes content to a file
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(path, content) {
    return $Call.ByID(1511688169, path, content);
}

// Private type creation functions
const $$createType0 = $models.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FileInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($$createType0);
