// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService handles project operations exposed to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateProject creates a new project at the given path
 * @param {string} name
 * @param {string} path
 * @param {string} description
 * @returns {$CancellablePromise<$models.Project | null>}
 */
export function CreateProject(name, path, description) {
    return $Call.ByID(3794430337, name, path, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetGitBranch returns the current git branch for the given path
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetGitBranch(path) {
    return $Call.ByID(3782054692, path);
}

/**
 * ListDirectory lists files in a directory
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function ListDirectory(path) {
    return $Call.ByID(3289437907, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListGitBranches returns all local git branches for the given path
 * @param {string} path
 * @returns {$CancellablePromise<string[]>}
 */
export function ListGitBranches(path) {
    return $Call.ByID(1498666676, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListProjects returns all recent projects
 * @returns {$CancellablePromise<$models.Project[]>}
 */
export function ListProjects() {
    return $Call.ByID(1083075410).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * OnStartup is called when the app starts
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function OnStartup(options) {
    return $Call.ByID(264003830, options);
}

/**
 * OpenProject opens a project by path and adds it to recent projects
 * @param {string} path
 * @returns {$CancellablePromise<$models.Project | null>}
 */
export function OpenProject(path) {
    return $Call.ByID(3378515093, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ReadFile reads a file from the filesystem
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(1365949130, path);
}

/**
 * SelectDirectory opens a native directory picker dialog
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(1192844387);
}

/**
 * SwitchGitBranch switches to the specified branch for the given path
 * @param {string} path
 * @param {string} branch
 * @returns {$CancellablePromise<void>}
 */
export function SwitchGitBranch(path, branch) {
    return $Call.ByID(1859568484, path, branch);
}

/**
 * WriteFile writes content to a file
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(path, content) {
    return $Call.ByID(1511688169, path, content);
}

// Private type creation functions
const $$createType0 = $models.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FileInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($$createType0);
